server:
  port: 9408

spring:
  application:
    name: corolla-base
  mvc:
    throw-exception-if-no-handler-found: true
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.18.128:8848

feign:
  httpclient:
    enabled: true