CREATE TABLE corolla_order (
	id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	user_id BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户id',
	is_delete TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
	create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
	order_msg_id BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '订单消息表id',
	PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT '订单表';

CREATE TABLE corolla_goods (
	id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(150) NOT NULL DEFAULT '' COMMENT '商品名称',
	price DECIMAL(10, 2) NOT NULL DEFAULT 0.00 COMMENT '价格',
	stock BIGINT(20) NOT NULL DEFAULT 0 COMMENT '库存数量',
	score DECIMAL(10, 2) NOT NULL DEFAULT 0.00 COMMENT '商品的积分',
	is_delete TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
	create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT '商品表';

CREATE TABLE corolla_user (
	id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(25) NOT NULL DEFAULT '' COMMENT '用户姓名',
	phone CHAR(11) NOT NULL DEFAULT '' COMMENT '用户手机号',
	account DECIMAL(20, 2) NOT NULL DEFAULT 0.00 COMMENT '用户账户余额',
	score DECIMAL(10, 2) NOT NULL DEFAULT 0.00 COMMENT '用户的积分',
	is_delete TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
	create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT '用户表';

CREATE TABLE corolla_order_goods (
	id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	order_id BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户id',
	goods_id BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '订单id',
	is_delete TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
	create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT '订单-商品表';

INSERT INTO corolla_user (`name`, phone, account, score) VALUES ('徐家俊', '13007151044', 5000, 0), ('胡迅', '17671791044', 8000, 0), ('谭启轩', '18271425350', 12000, 100);

INSERT INTO corolla_goods (`name`, price, stock, score) VALUES ('ipad2019', 4000, 300, 500), ('红米note8 Pro', 1000, 50, 100), ('安耐晒防晒霜', 210, 28, 20), ('无印良品爽肤水', 75, 38, 10);